export const GET_EPISODES = "GET/EPISODE/ALL";
export const LOADING = "LOADING/EPISODES";
export const PAGE = "EPISODES/PAGE";
export const NOT_FOUND = "NOT/FOUND/EPISODE";
export const EPISODE_SINGLE = "EPISODE/SINGLE";
export const GET_MULTIPLE_CHARACTER = "EPISODE/GET/CHARACTERS";
