export const GET_LOCATIONS = "GET/LOCATION/ALL";
export const LOADING = "LOADING/LOCATIONS";
export const PAGE = "LOCATIONS/PAGE";
export const NOT_FOUND = "NOT/FOUND/LOCATION";
export const LOCATION_SINGLE = "LOCATION/SINGLE";
export const GET_MULTIPLE_CHARACTER = "LOCATION/GET/CHARACTERS";
